{
 "title": "Circuit Breaker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_calls_seconds_count,application)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_calls_seconds_count{application=~\"$application\", cluster=~\"$cluster\"},instance)"
    }
   },
   {
    "name": "circuit_name",
    "label": "circuit_name",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", cluster=~\"$cluster\", instance=~\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Is Open?",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{application=\"$application\", cluster=~\"$cluster\", instance=~\"$instance\", name=\"$circuit_name\", state=\"open\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_max{application=\"$application\", cluster=~\"$cluster\", instance=~\"$instance\", name=\"$circuit_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{application=\"$application\", cluster=~\"$cluster\", instance=~\"$instance\", name=\"$circuit_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Calls Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_slow_calls{application=\"$application\", cluster=~\"$cluster\", instance=~\"$instance\", name=\"$circuit_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Count (1m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "delta(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", cluster=~\"$cluster\", instance=~\"$instance\", name=\"$circuit_name\", kind=\"failed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit Ignored Count (1m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "delta(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", cluster=~\"$cluster\", instance=~\"$instance\", name=\"$circuit_name\", kind=\"ignored\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}